### ISSUE TITLE
How to train lift with my own data?

### ISSUE THREAD

**Issue by qcl1994** [cvlab-epfl/tf-lift#15]
Hi, friends
Recently, I am working on how to train the LIFT with my own data, could you give me some instructions?
Thanks,
Steve Qiu

**Comment by kmyi** [comment]
Sorry, but as you can see, the codebase is not exactly plug-and-play, due to the complicated nature of the entire pipeline. We are only releasing the codes to give you a start point, and we unfortunately don't have enough time to provide support. We tried to leave as much comment in the code as possible for you to follow and create a data-io pipeline according to your dataset.

Thanks,
Kwang
