### ISSUE TITLE
tidy up of tf-lift and lift => how to train test, or run pretrained model 

### ISSUE THREAD

**Issue by essie-chiang** [cvlab-epfl/tf-lift#35]
Hi, 
I could not run tf-lift no matter I will train or run pretrain, I followed lots of pre-issues:

1. Train with raw data is not supported?
* Need read code to wrap raw dataset to h5 file?
https://github.com/cvlab-epfl/tf-lift/issues/9
linke mentioned: You can look into datasets/eccv2016.py
* Unable to open file scales-histogram-minsc-2.0.h5
https://github.com/cvlab-epfl/tf-lift/issues/5
Need read code and wrap data to scales-histogram-minsc-2.0.h5? But that is just training, could I train without this file?

2. Test:Need find LIFT repo 
However I find LIFT not able to run for it needs old Theano and old cuda...

My question is I am new to this area, and now is 2019, not reasonable to require support of a 2016 paper code. Could you just give some advise are there new projects that worth to follow? I am finding work that like LIFT, find better key point and image match than OpenCV.

Great thanks!

**Comment by kmyi** [comment]
Hi,

> 1. Train with raw data is not supported?

Indeed we cannot provide support for this. You'll need to study the code more carefully. To be honest, it's been a long time since this code was written, so we'll have to do the same.

> 2. Test:Need find LIFT repo

The test part should run without problems, given that you use the correct TF version, and the appropriate CuDNN libraries. I suggest using a docker instance with the correct version of TF.
