### ISSUE TITLE
Is there any related test code for Matching Score? 

### ISSUE THREAD

**Issue by RamboRick** [cvlab-epfl/tf-lift#46]
Thank you for your great work. 

I found that in the paper you use the matching score as an evaluation metric. 

I wonder is there any code available to calculating the Matching Score? Or any test code about this so that I can double-check? 

Also, is there any available library related with LIFT available on the mobile platform?

Thank you very much.

**Comment by kmyi** [comment]
Hi, w.r.t the evaluation, I suggest you see https://github.com/ubc-vision/image-matching-benchmark. We've moved on from matching scores since. 

Unfortunately, I am not aware of any LIFT implementations for mobile devices. TILDE keypoints have a C version, which I used to test on mobile, which works.

**Comment by RamboRick** [comment]
Thank you very much.
